/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Va2twJjk66lhBkX9Qe4YDPQZaNMp3aU+Z+a5YutZZRuUhAF6coXhT7OXUTp01d/+XIf4O+6XtpIf38nVRa+86A==
 */

/* eslint-disable */
// tslint:disable

import Links, {Links_InsertParameters} from './links'


interface DatabaseSchema {
  links: {record: Links, insert: Links_InsertParameters};

}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
