/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: cTMGd1OgsFTwiv9O0dY6rd3RsP10Aa7PY60UaWZuoX6ssU5HFgsuz7qYLjq6UIueJsjli1zpuYkI0nN/DXgexg==
 */

/* eslint-disable */
// tslint:disable

interface Links {
  original_link: string
  shortened_link: string
}
export default Links;

interface Links_InsertParameters {
  original_link: string
  shortened_link: string
}
export type {Links_InsertParameters}
